### ISSUE TITLE
Option for max results?

### ISSUE THREAD

**Issue by mmontag** [joshjung/trie-search#16]
Would it improve speed if the `ts.get('foo')` could return early when results reach an optional maximum? For example, I might have 24,000 matches but can only display 20 results at a time.

**Comment by joshjung** [comment]
@mmontag This is a really good idea. The issue of ordering will make this tricky to solve. Since the Trie is a structure that is built based on the insert order, if one could guarantee the insert order was always the same, then you could predictably limit the max results and not get a different 20 items each time.

I am not sure I will have time in the near future to tackle this, but if you make a PR and some tests I would gladly release a new version!

**Comment by williamburns** [comment]
Hi -- any update on this @joshjung ?
